# Set a plain language title for the site.
title: Mannerly-mail

# Write a short description for the site. This is used for "meta description."
description: A guided, opinionated email composition experience

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]
